---
# handy reference: http://stevejenkins.com/blog/2010/09/how-to-get-dkim-domainkeys-identified-mail-working-on-centos-5-5-and-postfix-using-opendkim/

- name: Install OpenDKIM and related packages
  apt: pkg={{ item }} state=installed
  with_items:
    - opendkim
    - opendkim-tools

- name: Create OpenDKIM config directory
  file: state=directory path=/etc/opendkim group=opendkim owner=opendkim

- name: Get virtual domains defined
  shell: PGPASSWORD="{{ mail_db_password }}" psql -U "{{ mail_db_username }}" -d "{{ mail_db_database }}" -h localhost -c 'SELECT array_to_json(array_agg(virtual_domains)) FROM virtual_domains;' -P "footer=off" | tail -n +3
  register: domain_rows_json

- name: Set the rows as a variable
  set_fact: mail_virtual_domains="{{ domain_rows_json.stdout | from_json }}"

- name: Create OpenDKIM key directories
  file: state=directory path=/etc/opendkim/keys/{{ item.name }} group=opendkim owner=opendkim
  with_items: "{{ mail_virtual_domains }}"

- name: Generate OpenDKIM keys
  command: opendkim-genkey -r -d {{ item.name }} -D /etc/opendkim/keys/{{ item.name }}/ creates=/etc/opendkim/keys/{{ item.name }}/default.private
  with_items: "{{ mail_virtual_domains }}"

- name: Put opendkim.conf into place
  copy: src=etc_opendkim.conf dest=/etc/opendkim.conf owner=opendkim group=opendkim
  notify:
    - restart opendkim
    - restart postfix

- name: Put additional OpenDKIM configuration files into place
  template: src=etc_opendkim_{{ item }}.j2 dest=/etc/opendkim/{{ item }} owner=opendkim group=opendkim
  with_items:
    - KeyTable
    - SigningTable
    - TrustedHosts
  notify:
    - restart opendkim
    - restart postfix

- name: Set OpenDKIM config directory permissions
  file: state=directory path=/etc/opendkim
          group=opendkim owner=opendkim mode=0700 recurse=yes
  notify:
    - restart opendkim
    - restart postfix
