---
# Installs and configures the Rspamd spam filtering system.

- name: Ensure repository key for Rspamd is in place
  apt_key: url=https://rspamd.com/apt-stable/gpg.key state=present

- name: Add Rspamd repository
  apt_repository: repo="deb https://rspamd.com/apt-stable/ {{ ansible_distribution_release }} main"

- name: Install Rspamd, Rmilter, and Redis, apt-transport-https for secure repo
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - rspamd
    - redis-server
    - apt-transport-https

- name: Start redis
  service: name=redis-server state=started

- name: Start rspamd systemd listener
  service: name=rspamd state=started
